package plugin

import (
	"google.golang.org/protobuf/reflect/protoreflect"
)

type enum struct {
	fd protoreflect.FileDescriptor
	f  *File
}

func (g enum) Generate() {
	g.f.P("// Code generated by protoc-gen-kratos-dart-http. DO NOT EDIT.")
	g.f.P()

	g.f.P(`// ignore_for_file: constant_identifier_names`)
	g.f.P()

	es := g.fd.Enums()
	for i := 0; i < es.Len(); i++ {
		if i > 0 {
			g.f.P()
		}
		g.enum(es.Get(i))
	}
}

func (g enum) enum(e protoreflect.EnumDescriptor) {
	g.f.P(`enum `, e.Name(), ` {`)

	vs := e.Values()
	for i := 0; i < vs.Len(); i++ {
		g.f.P(`  `, vs.Get(i).Name(), `,`)
	}
	g.f.P(`}`)
}
